############# Portuguese navigation ##############

# main menu
[[main]]
name = "Início"
url = "/"
weight = 1

[[main]]
name = "Biografia"
url = "/biografia"
weight = 2

[[main]]
name = "Milonga"
url = "/milonga"
weight = 3

[[main]]
name = "Aulas"
url = "/aulas"
weight = 4

[[main]]
# name = "Tango e Fado" # DELETED
# url = "/tango-e-fado" # DELETED
# weight = 5 # DELETED

# [[main]]
# name = "Blog"
# url = "/blog"
# weight = 6

# footer menu
# [[footer]]
# name = "Biografia"
# url = "/biografia"
# weight = 1

main = [{"name":"Início","url":"/","weight":1},{"name":"Biografia","url":"/biografia","weight":2},{"name":"Milonga d'A Barraca","url":"/milonga","weight":3},{"name":"Aulas","url":"/aulas","weight":4},{"name":"Tango e Fado","url":"/tango-e-fado","weight":5}]
