############# English navigation ##############

# main menu
[[main]]
name = "Home"
url = "/"
weight = 1

[[main]]
name = "Biography"
url = "/about"
weight = 2

[[main]]
name = "Milonga d'A Barraca"
url = "/milonga"
weight = 3

[[main]]
name = "Classes"
url = "/classes"
weight = 4