############# English navigation ##############

# main menu
[[main]]
name = "Home"
url = "/"
weight = 1

[[main]]
name = "Biography"
url = "/biography"
weight = 2

[[main]]
name = "Milonga d'A Barraca"
url = "/milonga"
weight = 3

[[main]]
name = "Classes"
url = "/classes"
weight = 4

[[main]]
name = "Tango & Fado"
url = "/tango-and-fado"
weight = 5