favicon = "images/favicon.png"
logo_text = "Alejandro Laguna"
navbar_fixed = true
theme_switcher = true
theme_default = "system"
mainSections = ["home","biografia"]
copyright = "Designed & Developed by Alejandro and [Guzman](https://github.com/guzmanlopez)."
[preloader]
enable = false
preloader = ""
[search]
enable = false
primary_color = "#121212"
include_sections = ["home","biografia","milonga","aulas","tango-e-fado","blog"]
show_image = true
show_description = true
show_tags = true
show_categories = true
[metadata]
keywords = ["Argentine Tango Lisbon", "Tango Classes Lisbon", "Milonga Lisbon", "Tango Portugal", "Traditional Milonga", "Tango and Fado", "Tango Teacher", "Tango Salon", "Villa Urquiza Style"]
description = "Argentine Tango in Lisbon with Alejandro Laguna. Professional classes, Milonga d'A Barraca since 1999. Where authentic Tango meets Fado in Portugal's capital."
author = "guzmanlopez"
[cookies]
enable = false
expire_days = 60
content = "This site uses cookies. By continuing to use this website, you agree to their use."
button = "I Accept"
[widgets]
sidebar = ["categories","tags"]
[google_map]
enable = false
map_api_key = "AIzaSyCcABaamniA6OL5YvYSpB3pFMNrXwXnLwU"
map_latitude = "38.7070606"
map_longitude = "-9.1552984"
map_marker = "images/marker.png"
