favicon = "images/favicon.png"
logo_text = "Alejandro Laguna"
navbar_fixed = true
theme_switcher = true
theme_default = "system"
mainSections = ["home","biografia"]
copyright = "Designed & Developed by Alejandro and [Guzman](https://github.com/guzmanlopez)."
[preloader]
enable = false
preloader = ""
[search]
enable = false
primary_color = "#121212"
include_sections = ["home","biografia","milonga","aulas","tango-e-fado","blog"]
show_image = true
show_description = true
show_tags = true
show_categories = true
[metadata]
keywords = ["tango argentino lisboa", "aulas de tango lisboa", "milonga lisboa", "tango portugal", "milonga tradicional", "tango e fado", "professor de tango", "tango salón", "villa urquiza", "aprender tango lisboa", "dançar tango portugal", "milonga d'a barraca", "alejandro laguna tango", "tango classes lisbon", "argentine tango lisbon", "milonga lisbon", "tango lessons portugal", "learn tango lisbon", "tango dance lisbon"]
description = "Tango Argentino em Lisboa com Alejandro Laguna. Aulas de tango, Milonga d'A Barraca desde 1999, e o projeto Tango & Fado. A referência do tango argentino em Portugal."
author = "Alejandro Laguna"
[cookies]
enable = false
expire_days = 60
content = "This site uses cookies. By continuing to use this website, you agree to their use."
button = "I Accept"
[widgets]
sidebar = ["categories","tags"]
[google_map]
enable = false
map_api_key = "AIzaSyCcABaamniA6OL5YvYSpB3pFMNrXwXnLwU"
map_latitude = "38.7070606"
map_longitude = "-9.1552984"
map_marker = "images/marker.png"
