# defaultContentLanguageInSubdir must be true for this to work.

# Other languages redirects
[[redirects]]
from = '/en/**'
to = '/en/404.html'
status = 404

# Default language must be last.
[[redirects]]
from = '/pt/**'
to = '/pt/404.html'
status = 404
